version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
     - '27017:27017'

  redis:
    image: redis
    container_name: redis
    ports:
     - '6379:6379'

  postgres:
    image: postgres
    container_name: postgres
    ports:
     - '5432:5432'

networks:
  default:
    external:
      name: local
