version: '2'

services:

  <%= name %>:
    build: ..
    image: quay.io/guidesmiths/svc-example:latest
    links:
     - mongo:mongo
     - redis:redis
     - postgres:postgres

  mongo:
    image: mongo

  redis:
    image: redis

  postgres:
    image: postgres
